default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/forecast_development.sqlite3

test:
  <<: *default
  database: db/forecast_test.sqlite3

production:
  <<: *default
  database: db/forecast_production.sqlite3
